### ISSUE TITLE
Stutter every 120 seconds

### ISSUE THREAD

**Issue by jeremynsl** [shiiion/dolphin#10]
Hi,

Firstly, thank you so much for Primehack.  What a way to go back and play though one of the best games ever made :D Awesome work!

So I've been playing through Prime 1 (in Trilogy) using the latest Primehack - Windows 10, GTX 1070, Ryzen 3600x.  I found that there were intermittent *hard* stutters when playing.  These differ from shader stutters etc.  If you just sit looking at a wall, they will happen about every 120 sec. I tried every possible shader setting, and every graphics API and they persisted.  

I tried the latest version of Dolphin without Primehack and did not see any stutters like this.  So I tried the Primehack .exe and I disabled Primehack in the configuration area and retested in the same area from the same savestate and after 10 minutes there wasn't a single hard stutter.  So it really does seem somehow related to the Primehack code.

I could produce a video of it, if that is useful?  I don't know what could be causing this - is there something that Primehack is polling every 2 minutes possibly?  Let me know if I can help with this please!

**Comment by SirMangler** [comment]
This is very interesting. PrimeHack is a state based system. PrimeHack runs on every frame, every frame it executes the same code which performs checks to see what it should be doing next (90% of the time that is simply updating camera movement, fov and other minor hacks), we do not handle any form of timers, parallel threading, etc. 

So, the problem only occurs with PrimeHack enabled. Hm. Could you please make a video?

- What FOV are you on?
- Do you have culling enabled? (PrimeHack GFX)
- Do you have "toggle arm adjustment" enabled? (PrimeHack GFX)
- Are you using mouse mode or controller mode?

Which room exactly? I would like to try to reproduce this.

**Comment by jeremynsl** [comment]
I will try to make a video.  Sometimes recording can effect frametimes etc but we'll see.

I am on 90 FOV, 20 sensitivity.
I have culling off.
Arm adjustment is on auto.  I also tried manual with the same results.
I am using mouse mode with default control mapping.

**Comment by jeremynsl** [comment]
Hi,

I've made two videos, the only difference is Primehack is turned off in the configuration page.  All other settings identical.  I'm in approximately the same spot in Phendrana Drifts as you can see.
[Primehack OFF](https://photos.app.goo.gl/fWkigWixn5shxaW19)
[Primehack ON](https://photos.app.goo.gl/FvY9erYozWWH7Ymb9)
(I forgot to turn off my mic for the recordings BTW, some extra noise in there.  I recorded at 1080p 60fps but google photos will take awhile to process so 360p right now)

You can see the stutter happen during the Primehack ON video at 1:40 and 3:40.  Since I'm running MSI afterburner with the frametime graph, you can visualize the stutter occurring as well.  With the Primehack OFF video there are no such stutters.

I haven't tried portable mode yet, first wanted to create these videos to show you what I'm experiencing.

**Comment by jeremynsl** [comment]
I don't know why, the videos aren't processing on Google Photos so I uploaded to Youtube
[Primehack OFF](https://youtu.be/5du43NPE-4E)
[Primehack ON](https://youtu.be/A04BEk2pwV4)

**Comment by ivanproff** [comment]
Same thing

**Comment by shiiion** [comment]
With an upcoming refactor in the pipeline, I haven't been able to replicate this consistently. I'll wait until that is release to re-evaluate this issue. Refactor should be released within the next 1-2 weeks.

**Comment by xmat123x** [comment]
I have it too but Primehack is just so good that after a bit I just ignore the stutters. Still it'd be nice to know what causes it.

**Comment by SirMangler** [comment]
Does anyone have the issue with the latest release?

https://github.com/shiiion/dolphin/releases/tag/1.0.1

**Comment by SirMangler** [comment]
We received report the 120 second stutter is now fixed in `v1.0.1` .

If anyone still has this issue, they can create a new issue with details of the problem on our newest version. For now this is closed for inactivity and a report it was fixed.
