### ISSUE TITLE
Toggle PrimeHack Controls setting always re-enabled on launch (Steam Deck Arch Linux)

### ISSUE THREAD

**Issue by nowickik** [shiiion/dolphin#101]
- Installed Primehack on steam deck using Discovery app. 
- Open Primehack , turned "Toggle PrimeHack Controls" off. 
- Close and reopen Primehack, setting is always back on. 

Verified in Dolphin.ini that EnablePrimeHack setting always switches to True.

This is a problem on the steam deck since you have to launch the game directly to play it from gaming mode and take advantage of the full steam deck support (suspend, paddle buttons, control mapping etc).

Launching Primehack from gaming mode and changing the setting each time you want to play doesn't work either since launching the game using this method results in the game running behind Primehack where you can't see it.

**Comment by SuperSamus** [comment]
This has already been fixed by 9ca0eb888bd6f8ed13a4efb92d808fbf0705ffa4.

**Comment by SirMangler** [comment]
> This has already been fixed by [9ca0eb8](https://github.com/shiiion/dolphin/commit/9ca0eb888bd6f8ed13a4efb92d808fbf0705ffa4). Though, a new version with the fix has yet to release.

This is actually the exact commit that the flatpak is based on, as some linux specific changes were added since the Windows release (1.0.5).

**Comment by AndehX** [comment]
Issue currently still present in v1.0.6.

**Comment by SirMangler** [comment]
Tested on the latest flatpak version (v1.0.7) on Fedora 40, the setting is saving as expected. Please open a new issue with the specific version and method of install (ie flatpak/aur/compiled) if you're experiencing this issue still, or feel free to ask in [our Discord](https://discord.gg/tchQne2).
