### ISSUE TITLE
Can't figure out how to use Mouse

### ISSUE THREAD

**Issue by ripps818** [shiiion/dolphin#107]
I'm using the Flatpak version on Fedora Linux. The game seems to run perfectly fine, performance is great in fact. but I am unable to properly control the game using the mouse because the mouse cusror doesn't actually bind to the game window. If I scroll past the window, it goes into my other monitor. I can't even select options on the bottom of the screen and am unable to turn around, suffice it to say, this makes it impossible to play.

**Comment by SirMangler** [comment]
This is a known issue with certain DE's and display managers (Wayland) but fixing it is ambiguous and seems to be dependent on the distro. We know it works on X11/Arch, I've seen some individuals find this was a permissions issue, their display manager wasn't letting PrimeHack control the mouse until it was given explicit permission. 

With the Qt frontend, we use Qt to centre the cursor:
https://github.com/shiiion/dolphin/blob/bd278b120a2c72d5fdfe8e1169d272cc128270bc/Source/Core/DolphinQt/RenderWidget.cpp#L69

**Comment by SirMangler** [comment]
Tested and found to be working on Fedora 40 with Wayland, on PrimeHack 1.0.7. Feel free to reopen the issue if you're still experiencing problems.
