### ISSUE TITLE
Crashes on M1 Mac

### ISSUE THREAD

**Issue by kevcube** [shiiion/dolphin#108]
This project crashes completely when beginning emulation on m1 Mac - this is a problem with Dolphin beta builds but not with nightlies, and would probably be fixed by pulling `upstream/master` into `master` here.

I'm trying to fix this myself...

**Comment by Yoyopizzacat** [comment]
how did you compile it?

**Comment by SirMangler** [comment]
Neither me or shio (the author) compiled Mac or added support for it personally. We aim to keep the repository up to date with the betas, unless you would like to merge it yourself, unfortunately you may need to wait until we get around to that.

**Comment by kevcube** [comment]
@Yoyopizzacat I downloaded this repository, set dolphin as the upstream, pulled from upstream, fixed conflicts, and built. then it worked. I'll push up to my personal fork.

**Comment by kevcube** [comment]
@Yoyopizzacat looks like I already pushed it. If you clone from [here](https://github.com/kevcube/dolphin) and build, you can run on m1 Mac.

**Comment by kevcube** [comment]
Output will be in `build/Dolphin.app`

**Comment by Yoyopizzacat** [comment]
@kevcube Thanks!

**Comment by Shock9616** [comment]
@kevcube Would you be able to post a precompiled version? I can't get it to finish compilation with either cmake or the `BuildMacOSUniversalBinary.py` script. Whenever I try to compile, both will either fail with a ton of warnings and errors, or will just hang and never finish.

**Comment by SirMangler** [comment]
The latest Mac build can be downloaded on our [releases page](https://github.com/shiiion/dolphin/releases) now, and newer versions can sometimes be found in our Actions page (if logged into github). Feel free to reopen this issue or ask in [our Discord](https://discord.gg/tchQne2) if you're having trouble with crashes.
