### ISSUE TITLE
How to compile for m1 Mac

### ISSUE THREAD

**Issue by Yoyopizzacat** [shiiion/dolphin#109]
I have tried for a few hours and followed the guide. It doesn’t work and I don’t know how to pull the submodules.

**Comment by SirMangler** [comment]
This is the latest guide for building dolphin on MacOS, replace any links to dolphin with links to primehack:
https://github.com/dolphin-emu/dolphin/wiki/Building-for-macOS

As this guide and the one on the readme says, you pull the submodules with:
`git submodule update --init`

Neither me or shio can directly help you with Mac related tasks, but the process should be identical to regular Dolphin.

Note there may be related issues according to https://github.com/shiiion/dolphin/issues/108

**Comment by Yoyopizzacat** [comment]
thanks!

**Comment by routerbad** [comment]
Compiling on Mac simply doesn't work. The reliance on Qt5 seems to be at least one issue it's running into as it isn't compatible with M1/M2 based Macs. Given Dolphin has native support of M1 silicon I would imagine this wouldn't be an issue.

**Comment by Yoyopizzacat** [comment]
> Compiling on Mac simply doesn't work. The reliance on Qt5 seems to be at least one issue it's running into as it isn't compatible with M1/M2 based Macs. Given Dolphin has native support of M1 silicon I would imagine this wouldn't be an issue.

It worked for me
