### ISSUE TITLE
compiled but crashes and there is error code

### ISSUE THREAD

**Issue by Yoyopizzacat** [shiiion/dolphin#111]
/Users/yoyochang/dolphin/Source/Core/MacUpdater/MacUI.mm:126:7: warning: 'launchApplication:' is deprecated: first deprecated in macOS 11.0 - Use -[NSWorkspace openApplicationAtURL:configuration:completionHandler:] instead. [-Wdeprecated-declarations]
      launchApplication:[NSString stringWithCString:path.c_str()
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWorkspace.h:379:1: note: 'launchApplication:' has been explicitly marked deprecated here
- (BOOL)launchApplication:(NSString *)appName API_DEPRECATED("Use -[NSWorkspace openApplicationAtURL:configuration:completionHandler:] instead.", macos(10.0, 11.0));
^
1 warning generated.
[100%] Linking CXX executable "../../../Binaries/Dolphin Updater.app/Contents/MacOS/Dolphin Updater"
Compiling Storyboard Main.storyboard...
/* com.apple.ibtool.document.notices */
/Users/yoyochang/dolphin/Source/Core/MacUpdater/Main.storyboard:r87-pn-Exw: note: NSTextField's height does not match its intrinsic content size, use "Size to Fit Content" to correct [22]
/* com.apple.ibtool.document.warnings */
/Users/yoyochang/dolphin/Source/Core/MacUpdater/Main.storyboard:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
Copying OS X content Binaries/Dolphin Updater.app/Contents/Resources/Dolphin.icns
[100%] Built target MacUpdater
[100%] Building CXX object Source/UnitTests/CMakeFiles/unittests_stubhost.dir/StubHost.cpp.o
[100%] Built target unittests_stubhost

**Comment by Yoyopizzacat** [comment]
I have no idea what to do

**Comment by SirMangler** [comment]
This log seems to show that the compilation was successful. Copying resources is a post-build action. Search your build folders for a `dolphin-emu` binary. It may be in a folder marked `Binaries` or `bin`. As I have never used Mac before, I cannot tell you the precise output location or executable name.

If you cannot find said executable, please make a pastebin with the entire output log of the compilation, ideally including the commands you used to build.

**Comment by Yoyopizzacat** [comment]
app just crashes on launch

**Comment by SirMangler** [comment]
This sounds like it might be a duplicate of https://github.com/shiiion/dolphin/issues/108 then. You may need to wait until the repository is updated to see if upstream has resolved this issue.

**Comment by Yoyopizzacat** [comment]
fixed

**Comment by Yoyopizzacat** [comment]
.
