### ISSUE TITLE
Flatpak Dolphin Config Folder location

### ISSUE THREAD

**Issue by Bungeetaco** [shiiion/dolphin#112]
Hi there,

I got PrimeHack running on my Steam Deck via Flatpak installation, but I would also like to load custom textures.
Is this possible through the Flatpak build? If so, does anyone know where the Dolphin config folder would be located on Linux?

Thanks in advance

**Comment by SirMangler** [comment]
Just in case you still need to know, the config folder would be in `~/.var/app/io.github.shiiion.primehack/config/dolphin-emu/`
