### ISSUE TITLE
map menu uses the morphball profile

### ISSUE THREAD

**Issue by ProfessionalismIsMyMiddleName** [shiiion/dolphin#114]
Playing MP1 in trilogy, with a controller.
I just noticed it after changing the mapping of B in morphball, I had it the same as the main profile B until now so I didn't notice it.

That seems a bit counter-intuitive, is it intended behaviour? 

Sorry for creating multiple issues btw, I thought it would be better to report them

**Comment by SirMangler** [comment]
> is it intended behaviour

You'll find that the setting name is called 'Morphball / Map Profile', so yes, it is. 


![image](https://user-images.githubusercontent.com/4237834/183217257-10614fe0-148f-4822-b9d3-7c93cff6a8fe.png)

B in Biped would be jump (unless you inverted it in the in-game settings)
B in Morphball is boostball
B in Map is Back

in my personal opinion, it makes less sense to have 'Back' on Space/Jump and would be better suited to Shift, with the new map controls enabled, which would also make sense for boostball, as Springball on the same key  as Biped jump is more intuitive. 

That said, the feature was made in mind for differing movement controls between the three modes, so not never scenario was considered. If you're not using the new map controls, Shift for Back isn't a terrible substitute, seeing as 'Space' itself is already a little weird.

**Comment by ProfessionalismIsMyMiddleName** [comment]
> You'll find that the setting name is called 'Morphball / Map Profile', so yes, it is.

Dammit, I thought the "map" meant "key mapping". I guess it makes sense now.

I'm playing on controller, and put both biped jump and spring ball on B, It seemed logical to have the jump button be the same for both modes.

Would it make sense to separate morphball profile and map profile? That could be useful in some cases I suppose?

Anyway, since it's intended behaviour, there is no problem, you can close the ticket I guess.
