### ISSUE TITLE
[Linux] Vulkan renderer crashes emulation instantly, runs fine with OpenGL

### ISSUE THREAD

**Issue by cyrv6737** [shiiion/dolphin#115]
Running Metroid Prime Trilogy with the Vulkan renderer causes the emulation to stop pretty much instantaneously while OpenGL renderer plays the game fine.

I am using the Flatpak release, v1.06a. Both mesa and mesa-git Flatpak drivers produce this behavior. I also tried the `dolphin-emu-primehack-git` AUR package via Distrobox podman container, and this also produced the same behavior.

Distro: Nobara
Kernel: 5.19.4-201.fsync.fc36.x86_64
CPU: 5900x
GPU: 6900 XT

**Comment by SirMangler** [comment]
If you're still experiencing problems, please feel free to reopen this issue or ask in [our Discord](https://discord.gg/tchQne2).
