### ISSUE TITLE
1.06 Metroid Controller Configuration not Working

### ISSUE THREAD

**Issue by hcook95** [shiiion/dolphin#116]
Tested on both commit 9190dcecf760cd20e0d5385c1870f9019dc690ce and tag 1.0.6a on Ubuntu 22.04. When I go into Controller Settings --> Metroid Controller Configuration and change the configuration from the default to a custom configuration, the game (Metroid Prime Trilogy) still uses the default configuration.

**Comment by SirMangler** [comment]
To be clear, are you changing the GameCube controls, or the Wii controls? Metroid Prime Trilogy is a Wii game.

**Comment by hcook95** [comment]
Ok, I see part of my mistake. I was changing the Metroid Controller

**Comment by SirMangler** [comment]
Thanks for reporting! That broke when we updated PrimeHack with the newer beta of dolphin.

https://github.com/shiiion/dolphin/commit/efb99ebfd20b1bc16ea3e51fec409c91e354d8c2


The updated flatpak will processing in about an hour.
