### ISSUE TITLE
Changing visor modes occasionally creates audio issues

### ISSUE THREAD

**Issue by Zhnigo** [shiiion/dolphin#12]
Sup! Thanks for your work!

I'm experiencing a bug where changing visor modes will occasionally lead to the scan visor's ambient hum being present even when the scan visor isn't on, and it seems to be cumulative, the sound eventually starts playing many times over itself to the point it nearly drowns out other audio. This seems to happen often when switching from scan visor to combat visor in the middle of scanning, or in the middle of reading a multiple-page scan report. Also seems to happen when switching the scan visor on during a cutscene.

Thanks in advance, and I'll be happy to provide any details.

**Comment by SirMangler** [comment]
1. Which game in particular (or is it all?) and which region? 

2. Which OS/platform?

3. Does this problem occur on all of the DSP Emulation Engines? (See the `Config > Audio` tab). 

4. Which audio backend are you using? You can find this in the same place as the DSP Emulation stuff.

5. Lastly can you please go to your `Game Properties > Verify` and verify the integrity of your dump? If any problems show in the window, could you please provide a screenshot? 

As for trying to resolve this issue, does this occur when you use the default settings?

On Windows, you can enable portable mode by adding `portable.txt`, which if you don't already know, will temporarily make Dolphin use the local `./User/` folder as your settings location, thus making it generate the default settings. On Linux you will have to rename your settings folder. 

Please do not change any settings (other than adding your game folder and your save).

Thank you!

**Comment by Zhnigo** [comment]
Thanks for the quick reply! 

1. So far only tested on the first MP, iso is MP Trilogy for Wii, USA region.
2. Win10
3. It occurs on HLE Emulation and LLE Recompiler, haven't tested on LLE interpreter as running it makes the emulation way too slow.
4. Cubeb
5. All good here

As for running on default settings, I'll try it later this day and come back to you with results, as well as hopefully more detailed circumstances of when/if the issue occurs.
Cheers!

**Comment by Zhnigo** [comment]
Hello again
On default settings the problem still persists. The easiest way to replicate is to scan something, then when the text appears, without releasing the scan button, change the visor from scanner to combat. The scanner's ambient hum will persist.

**Comment by SirMangler** [comment]
I am able to reproduce this problem. We will look into resolving this soon. Perhaps making it so that you cannot change visor while scanning something, if we can find a flag for that in all three games.

**Comment by SirMangler** [comment]
Fixed: https://github.com/shiiion/dolphin/commit/ab43100e715479f876177212176549101b15fc8a
