### ISSUE TITLE
Fire missiles with the middle click

### ISSUE THREAD

**Issue by Kekun** [shiiion/dolphin#121]
Hi, I recently started using PrimeHack and one of the main usability issues I had was firing misiles while strafing right (it's particularly a problem in boss fights). I switched firing missiles from `F` to `Click 2` (the middle click) and the game instantaneously became much more playable to me, I can lock on an ennemy with the right click, stafe right with D and fire missiles with the middle click all at once. :slightly_smiling_face: My philosophy is to use the defaults and to make them evolve, hence my suggestion to change the default. For backwards compatibility, the new layout could be `F | "Click 2"`.

**Comment by esanscoopsers** [comment]
I second this

**Comment by SirMangler** [comment]
After 2 years of development we have finally pulled it off. Missiles are now F or Middle Click!
