### ISSUE TITLE
Prime Hack/Dolphin stops running as soon as started!

### ISSUE THREAD

**Issue by williambroad** [shiiion/dolphin#124]
Hey folks.

I have been scratching my head over a problem I can't seem to solve even though I've researched dozens of sites and tried out many many ideas. Here's what's going on...

So I've installed Prime Hack as seen in various tutorials which wasn't complicated at all.
Running the Updater the first time after a successful install opens the emulator and the game runs just fine. After that I stop the emulation and set up the configuration/graphics/controller etc...
From then on, no matter when and how I open the emulator again - be it through dolphin.exe or the Prime Updater application - it opens but instantly comes to a halt and appears to have crashed (that's what I thought at least the first couple of times). But then I took a look at the recource monitor to find out that dolphin.exe has just been halted (blue font in resource monitor) which I then am able to continue.

Since I would like to set up running Prime Hack through a front end program (Launchbox) and play it on the couch using only a controller it's really annoying to be forced to use keyboard/mouse to open up the resource monitor each time and give dolphin.exe a push to continue working.

I tried every different version, even Ishiiruka fork (which seems to work more stably but only gives me a black screen after the Wii warning screen). But nothing solves this weird problem. And it's really the only program that does that, too.

I have just finished installing it on my Steam Deck and it runs flawlessly out of the box as it should.
So something must be interfering with dolphin.exe.
It's none of my programs that run at Windows (10 Pro btw) startup (Afterburner, iCue, Geforce Experience  etc...) nor is it the Anti-Virus software since I tried to exclude everything from being scanned.

So if anyone should have an idea of what's going on I would gladly appreciate it.

Cheers,
Matt

![Screenshot](https://user-images.githubusercontent.com/89192171/203827706-94345d3f-1bf4-4f16-95cf-454c4ea58f3f.png)

**Comment by SirMangler** [comment]
If you're still experiencing problems, please feel free to ask in [our Discord](https://discord.gg/tchQne2)
