### ISSUE TITLE
[Wiki] Settings for flickering logo/black bar bug

### ISSUE THREAD

**Issue by SkyNinja** [shiiion/dolphin#126]
So, after experimenting for an hour or two, I found that, in my case at least, setting `Deterministic dual core` to `none` eliminated the flickering logo bug in-game and kept the full performance improvements of dual core. From there, I found that enabling `Immediately Present XFB` fixed the purple loading screen and no longer resulted in the black bar. 

These settings may not work for everyone, but they do have the game (Trilogy) running at full speed with none of the visual bugs that dual core can cause without `Synchronize GPU thread` enabled.

**Comment by SkyNinja** [comment]
As it turns out, this is also inconsistent. It helped on several runs, but sometimes these issues still occur. However, before changing  "Deterministic dual core", it was constant. Now, it's just occasional, so it seems to alleviate the issues somewhat.

**Comment by SirMangler** [comment]
The wiki settings were tailored to solve these problems for "most" machines and so unfortunately tweaking is still required in some cases, but we know a lot more about how these settings and dual core related bugs occur now. We intend on updating the wiki at a later date.
