### ISSUE TITLE
[bug] VRAM not clearing after ending emulation, only on closing Dolphin itself

### ISSUE THREAD

**Issue by braezer** [shiiion/dolphin#128]
while trying to optimise/verify/increase my settings, I noticed in GPU-z that the Memory Used was ~1.8GB which seemed odd. I closed Dolphin completely and it went down to 750MB. to confirm my suspicions whether it was a consistent behaviour or an oddity from constantly changing settings, I launched Dolphin and went into game where Memory Used went up to about 900mb, ended emulation and it stayed there so I started the game up again, went up to about 1GB, then once again it went to 1.1GB, without changing the settings at all or closing dolphin between game boots. upon closing Dolphin, it went back down to 750MB once more.

edit: forgot to mention this was using DX12 on Prime 1 GM8E01

**Comment by vyuuui** [comment]
As in the case of #129, please report this to Dolphin, not Primehack. It'll get much better visibility there if it is actually an issue.
