### ISSUE TITLE
[1.0.6a] Prime 3 freeze on save load. (similar crashes for prime 1 and 2)

### ISSUE THREAD

**Issue by SilverDash** [shiiion/dolphin#130]
Vanilla and Rando versions (rando being unpacked)

will consistently crash causing the game to go to 0 fps.

log spits out these lines endlessly in a loop. 

below are the exact moments the crash happens.  

``33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:102 N[PowerPC]: == STACK TRACE - SP = 809a27a0 ==
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 804f35cc ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 804e5450 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 804e55e4 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 803f6284 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 803f6854 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 802eb548 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 804defe8 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 8041fe10 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 00000000 ]
33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]:  *  ---  [ addr = 8041fe10 ]
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:335 N[PowerPC]: 
IntCPU: Unknown instruction 00000000 at PC = 80004000  last_PC = 8132ffc8  LR = 80539564
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r0: 0x00000000 r1: 0x809a27a0 r2: 0x806869c0 r3: 0x806455a5
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r4: 0x80645024 r5: 0x00000040 r6: 0x8064559f r7: 0x00000000
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r8: 0x8060ffe0 r9: 0x8060ff60 r10: 0x0000c208 r11: 0x809a27c0
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r12: 0x804f347c r13: 0x806801c0 r14: 0x00000000 r15: 0x00000000
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r16: 0x00000000 r17: 0x00000000 r18: 0x00000000 r19: 0x00000000
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r20: 0x00000000 r21: 0x00000000 r22: 0x000000ff r23: 0x8060b418
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r24: 0x00000000 r25: 0xd1dd0d1e r26: 0x05fc5fc4 r27: 0x80644cb8
33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r28: 0x8064559f r29: 0x806455a5 r30: 0x00000000 r31: 0x80644be0``

![image](https://user-images.githubusercontent.com/5953198/208010947-f8de0fa4-1a90-4b2e-b303-0f6718a77d6b.png)

![image](https://user-images.githubusercontent.com/5953198/208010967-da3e6bc8-2a44-44df-bc47-efadb29ce064.png)

The crashes that happen for prime 1 and prime 2 (GCN) happen when the game hitches. Any time a hitch happens the game has a huge chance to just freeze causing a crash. 

The log for it is similar if not the exact same. 

All roms are and have been freshly dumped from my wii. 

All run with no issues on Current dolphin builds. Rando or vanilla.

If you need additional information let me know and I'll do my best to provide all that is needed.

**Comment by SilverDash** [comment]
![image](https://user-images.githubusercontent.com/5953198/208220453-6a29ecb9-0b41-471c-a783-508ae8126d13.png)

**Comment by braezer** [comment]
weird, I just played MP1 from start to finish but using version GM8E01 instead of my PAL copy (due to changes in patches between these versions). what version are you using? also, I noticed you're using the Interpreter core, have you tried using the JIT recompiler? if not, or either way, have you overclocked it? (I have mine on 250% because it loaded my normal dolphin settings before I made it portable mode and didn't bother changing it back by the looks of it. needed for the disc speed up transfer rate anyway iirc)

it took me a long time to solve the hitches but it was definitely worth it, turns out for me the main problem was the audio so I had to stick to DSP HLE on the Cubeb backend with an audio stretching of 160ms to stop it (without the stretching it would still hitch, after that it would only hitch when I cranked up the anti-aliasing to 8x which would crank my GPU to its absolute limits for a couple frames lol)

**Comment by vyuuui** [comment]
> but using version GM8E01 instead of my PAL copy (due to changes in patches between these versions). what version are you using? also, I noticed you're using the Interpreter core, have you tried using the JIT recompiler? if not, or either way, have

Jit is being used, the log says interpreter because if an unknown instruction is executed, dolphin falls back to the interpreter.

Regardless, this is an issue with *Rando* crashing, not perf on the vanilla games.

**Comment by vyuuui** [comment]
> Vanilla and Rando versions (rando being unpacked)
> 
> will consistently crash causing the game to go to 0 fps.
> 
> log spits out these lines endlessly in a loop.
> 
> below are the exact moments the crash happens.
> 
> `33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:102 N[PowerPC]: == STACK TRACE - SP = 809a27a0 == 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 804f35cc ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 804e5450 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 804e55e4 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 803f6284 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 803f6854 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 802eb548 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 804defe8 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 8041fe10 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 00000000 ] 33:21:522 Core\Debugger\Debugger_SymbolMap.cpp:118 N[PowerPC]: * --- [ addr = 8041fe10 ] 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:335 N[PowerPC]: IntCPU: Unknown instruction 00000000 at PC = 80004000 last_PC = 8132ffc8 LR = 80539564 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r0: 0x00000000 r1: 0x809a27a0 r2: 0x806869c0 r3: 0x806455a5 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r4: 0x80645024 r5: 0x00000040 r6: 0x8064559f r7: 0x00000000 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r8: 0x8060ffe0 r9: 0x8060ff60 r10: 0x0000c208 r11: 0x809a27c0 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r12: 0x804f347c r13: 0x806801c0 r14: 0x00000000 r15: 0x00000000 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r16: 0x00000000 r17: 0x00000000 r18: 0x00000000 r19: 0x00000000 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r20: 0x00000000 r21: 0x00000000 r22: 0x000000ff r23: 0x8060b418 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r24: 0x00000000 r25: 0xd1dd0d1e r26: 0x05fc5fc4 r27: 0x80644cb8 33:21:522 Core\PowerPC\Interpreter\Interpreter.cpp:339 N[PowerPC]: r28: 0x8064559f r29: 0x806455a5 r30: 0x00000000 r31: 0x80644be0`
> 
> ![image](https://user-images.githubusercontent.com/5953198/208010947-f8de0fa4-1a90-4b2e-b303-0f6718a77d6b.png)
> 
> ![image](https://user-images.githubusercontent.com/5953198/208010967-da3e6bc8-2a44-44df-bc47-efadb29ce064.png)
> 
> The crashes that happen for prime 1 and prime 2 (GCN) happen when the game hitches. Any time a hitch happens the game has a huge chance to just freeze causing a crash.
> 
> The log for it is similar if not the exact same.
> 
> All roms are and have been freshly dumped from my wii.
> 
> All run with no issues on Current dolphin builds. Rando or vanilla.
> 
> If you need additional information let me know and I'll do my best to provide all that is needed.

Lovely... more randomizer problems. If you could list what seed you are using, as well as any special settings you have that aren't default, that would help in trying to debug this.

 Also, I'm guessing this is MP3 standalone, not a part of the trilogy? Need to be 100% sure.

**Comment by SilverDash** [comment]
This was an issue with vanilla. All prime games too. Most of the loading crashes with prime 3 were fixed with a redump.

All that remains is the similar crashes when doing anything that cause the emulator to freeze even a little bit.

**Comment by SirMangler** [comment]
If you're still experiencing these issues on PrimeHack with a clean dump, please reopen this issue or ask on [our Discord](https://discord.gg/tchQne2).
