### ISSUE TITLE
[Linux, KDE] Mouse clicks within window are not registered

### ISSUE THREAD

**Issue by TheGag96** [shiiion/dolphin#132]
OS: Artix Linux x64, KDE Plasma (5.26.1)
Game: Metroid Prime 1 GCN (Rev 0)
Version: master @ da360b0

With the Default keybindings, PrimeHack correctly captures the mouse within the window, but clicking inside it doesn't actually trigger the `Click 1` binding. Clicking the window's titlebar or icon on the taskbar works, strangely enough...

Somewhat related: How do you hide the mouse cursor, especially in fullscreen? Do I need to tweak something in KDE?

Thanks!

**Comment by EnderMaster77** [comment]
Experiencing same issue here in Pop!_Os 22.04 LTS, GNOME 42.3.1.

**Comment by vyuuui** [comment]
If you go to the about section, does it mention what version of Qt it is using? Some version of Qt6 broke mouse input on Linux, so we should be using Qt5.15 or so.

**Comment by EnderMaster77** [comment]
> If you go to the about section, does it mention what version of Qt it is using? Some version of Qt6 broke mouse input on Linux, so we should be using Qt5.15 or so. I'll attempt to build myself and see results.

I'm using  QT 5.15.7.

**Comment by EnderMaster77** [comment]
After a bit more investigation, I found that while it does detect clicks, It doesn't detect if you let go of the mouse button, so it overrides any actual input with M1 being pressed down.

**Comment by EnderMaster77** [comment]
After even more investigation, this bug only happens when opening a normal instance of dolphin and then opening primehack, which will cause stock dolphin to detect mouse input normally and primehack experience this bug. Interestingly, if you open primehack first, then dolphin, stock dolphin experiences this bug.

**Comment by hazelnot** [comment]
I'm using the Flatpak release and running into this issue as well, and it seems like it uses Qt 6.5.2. I don't know if the Flatpak is maintained by the same people who maintain the project as a whole, but shouldn't a Flatpak use a known working version of Qt? 😅

**Comment by Rednax35** [comment]
Started having this same issue via the Flatpak install on Fedora 38, using Qt 6.5.2. It simply doesn't recognize mouse clicks at all. I can still move the mouse and navigate the menu by changing the Shoot (A) button to a key on my keyboard, but other than the mouse control is borked.

**Comment by AsurasWrathX** [comment]
Same issue here, Flatpak Installation Version 1.0.6a on Fedora 38.
Mouse Movement gets registered fine, but clicks do nothing

**Comment by pizzadude** [comment]
Same problem. Decided to run it in wine for now. Used wine-ge-proton with lutris. Make sure to set opengl or vulkan.

**Comment by medguy28** [comment]
Same issue here on fedora 38 and flatpak install version 1.0.6a

**Comment by pizzadude** [comment]
Update: I use Warehouse ( https://flathub.org/apps/io.github.flattool.Warehouse ) to downgrade the Primehack flatpak to the last commit from 2022 and that fixes it, for now. You can also use the flatpak CLI to downgrade, if you don't want to use Warehouse.

**Comment by pizzadude** [comment]
This isn't an issue for me anymore with latest primehack flatpak, on Fedora 40 KDE (Plasma 6).

**Comment by SirMangler** [comment]
Per pizzadude, I cannot recreate this on Fedora 40 on Wayland on PrimeHack 1.0.7. If this is still an issue, feel free to reopen this or create a new issue and specify if you're on X11 or Wayland.
