### ISSUE TITLE
[bug] widescreen hack resizing to 4:3 and back on the final boss in MP1 GM8E01

### ISSUE THREAD

**Issue by braezer** [shiiion/dolphin#133]
did a little trial of widescreen to try help a fellow who posted here and found the old bug is still present, and found this post regarding it on reddit from 2 years ago:

> [PyroPaperPlanes](https://www.reddit.com/user/PyroPaperPlanes/)
>[2 yr. ago](https://www.reddit.com/r/DolphinEmulator/comments/jkfc65/comment/gaj557u/?utm_source=reddit&utm_medium=web2x&context=3)
>· edited 2 yr. ago

>A somewhat recent revision in Dolphin ([5.0-11841)](https://dolphin-emu.org/download/dev/c0ae9cbc453d1e62e7bce9ad05c84de92ac24560/), while fixing some widescreen issues, has also unfortunately broken Dolphin's "Widescreen Hack" option for certain games; both Metroid Prime and Metroid Prime 2: Echoes has been affected by this bug. The last working revision was 5.0-11838 which can be acquired [here](https://dolphin-emu.org/download/dev/master/5.0-11838/). Direct link: https://dolphin-emu.org/download/dev/master/5.0-11838/

I can supply my save file if needed/wanted to test, as it is literally just before the final boss (not 100% on the energy packs and missiles, but close enough)

this is on the GM8E01 version of Metroid Prime for the Gamecube as a .ciso, using widescreen hack + force 16:9 + disable culling.

**Comment by vyuuui** [comment]
This is a known issue with dolphin's aspect ratio detection, as mentioned by Jos I believe. There's not much Primehack can do about this, though. This is a bug that needs to be fixed upstream.

**Comment by Skywolf285** [comment]
Add

```
[Video_Settings]
SuggestedAspectRatio = 3
```

To your GameINI for any game with these issues to get around Dolphin's somewhat unreliable Heuristic Widescreen detection. Simply right click the game in your game list, _Properties_ -> _Editor_ -> _User Config_.

Source: https://github.com/dolphin-emu/dolphin/blob/0900e68986a4fa2254fb3c459f73af4815979e45/Source/Core/VideoCommon/RenderBase.cpp#L1277

**Comment by SirMangler** [comment]
Generally the fix here is to force an aspect ratio and not rely on the broken heuristic as said above. Changing the ini files directly usually isn't necessary.
