### ISSUE TITLE
FR: Skip Gamecube IPL When Not Present and "Skip Main Menu" is False

### ISSUE THREAD

**Issue by rehashedsalt** [shiiion/dolphin#136]
In its default configuration, PrimeHack reads vanilla Dolphin configuration files when present. This caused an issue for me where, upon launching Prime through PrimeHack, the game immediately closed with no error message. I was able to trace this to Settings > Gamecube > "Skip Main Menu", which was unset as I normally use the IPL on vanilla Dolphin. However, my PrimeHack installation was not provided a copy of the IPL, so it attempts to launch the IPL and fails silently.

Replication steps:
* Launch Vanilla Dolphin with a copy of the IPL installed
* Disable "Skip Main Menu"
* Launch PrimeHack
* Launch any game through PrimeHack
* Be confused as to why it instantly closed

Couple possible solutions:
* Ignore "Skip Main Menu" when the IPL cannot be found
* Always skip the IPL (since it's PrimeHack and who's actually going to use the IPL on PrimeHack)
* Provide an error message to the user when the IPL cannot be found (there's one if you turn on the debugger UI but that's an incredibly non-obvious troubleshooting step -- it's suppressed otherwise)

**Comment by SirMangler** [comment]
This sounds more like an issue going between two majorly different Dolphin versions, PrimeHack doesn't do anything differently from vanilla dolphin while you're not running a supported Metroid title. If PrimeHack is sharing the same settings as regular dolphin (ie to see that Skip Main Menu is enabled), it would have the same paths to your IPL as well. Please re-open this issue if this still exists with clean configs on the latest PrimeHack version.

**Comment by rehashedsalt** [comment]
I've since swapped to Linux and am unsure what the versions I tested with were. Either way, this issue is stale and niche so I concur with closing. If it bites anyone else they'll open an issue.
