### ISSUE TITLE
Optional custom HUD texture for on-screen button prompts and the like?

### ISSUE THREAD

**Issue by NintendoManiac64** [shiiion/dolphin#137]
Any chance of integrating the following excellent custom HUD for on-screen button prompts and the like in some fashion?:
- https://forums.dolphin-emu.org/Thread-metroid-prime-trilogy-hd-interface-textures-v-1-7-may-01-2021?pid=527477#pid527477

**Comment by SirMangler** [comment]
This might be what you're looking for, based on a feature in Dolphin:
https://forums.dolphin-emu.org/Thread-universal-dynamic-input-2-0-02-16-a-custom-button-pack-for-over-150-games

**Comment by NintendoManiac64** [comment]
I am aware of that as it was linked in that same thread I mentioned.

Nevertheless, I was inquiring specifically about including and/or bundling something with PrimeHack for more "plug-and-play" functionality rather than requiring the user to import it themselves, especially since it'd be useful for actually learning the controls used in PrimeHack when starting a game from the beginning.

**Comment by SirMangler** [comment]
This UI pack has different defaults from us, and doesn't support multi-key binds like "E + 2" like our defaults use, plus it doesn't help if the user is on a SteamDeck or is using a controller. Good button prompts is an issue that still hasn't been solved by anyone in the community afaik, with the best attempt being what I linked before, we would have to develop our own mod to add better prompts and more room for the icons. As of right now we have no interest in integrating that particular texture pack.
