### ISSUE TITLE
Mouse not working in main menu

### ISSUE THREAD

**Issue by Marzipas** [shiiion/dolphin#138]
When launching into Metroid Prime Trilogy I'm unable to select anything in the menu as it doesn't appear to register any mouse movement (albeit the calibration options in Dolphin detect the mouse movement). I can click to go back and forth between the start screen and the actual menu but aside from that I'm unable to click anything.

**Comment by SirMangler** [comment]
If you still have this problem, please ask in [our Discord](https://discord.gg/tchQne2).
