### ISSUE TITLE
Auto Toggle EFB not Under PrimeHackGFX menu

### ISSUE THREAD

**Issue by Axel-of-the-Key** [shiiion/dolphin#140]
This option mentioned in the Wiki, which is required for Metroid Prime 3's visor changing to work, is not under the PrimeHackGFX menu despite supposedly being there.
![image](https://user-images.githubusercontent.com/8282745/222022561-6f777d30-9b14-4a0e-96c6-654296fda56f.png)

**Comment by SirMangler** [comment]
It's enabled by default. It was removed from the UI because we had too many users complaining that scan visor doesn't work after they turned off our fix for scan visor.

**Comment by Axel-of-the-Key** [comment]
Well. The scan visor doesn't work. 🤣

**Comment by vyuuui** [comment]
> Well. The scan visor doesn't work. 🤣

What do you mean by “doesn’t work”

**Comment by Axel-of-the-Key** [comment]
Playing Metroid Prime Trilogy version of Metroid Prime 3 in PrimeHack. When I press the button assigned to the "Minus" button, the visor-changing UI does not appear on my screen. I can tell that the button is properly bound because when I get to the tutorial and point my reticle at the object that needs to be scanned, after pressing the keyboard button I have bound to "Minus" tutorial text pops up telling me to point my visor to the upper part of the screen. However, with no change to the UI I cannot access the ability to change visors, making me permanently stuck.

**Comment by vyuuui** [comment]
https://github.com/shiiion/dolphin/wiki/Installation#beams-and-visors
please read this, and the “efb” fix you are referring to was for not being able to scan, not related to visor switching.

**Comment by Axel-of-the-Key** [comment]
Thank you!
