### ISSUE TITLE
Prime Hack closes itself after 2 ~ 5 seconds after opening

### ISSUE THREAD

**Issue by MTSYuki** [shiiion/dolphin#146]
In the first install and configuring the emulator, i'll run fine with all possible configurations. After I closed the emulator and opened again, i'll open normally until 2 to 5 seconds the emulator will crash. Nothing seems to indicate what was the fault (Even checking the log don't seems to actually show what was wrong). The only thing the log indicate is

`Qt: Session management error: Could not open network socket`

Even reinstall the problem persists.
I should mention this is the Flatpak version, never tested other versions.

**Linux Fedora 38**
**CPU: I3-10110U**
**8Gb Ram**
**KDE Plasma 5.27.7**
**QT: 5.15.9**

**Comment by SirMangler** [comment]
If you still have this problem, please ask in [our Discord](https://discord.gg/tchQne2).
