### ISSUE TITLE
can't run on wayland

### ISSUE THREAD

**Issue by B-Nerd** [shiiion/dolphin#150]
it does not work on wayland i double clicked primehack the flatpak version & it did not launch i  ran it via the terminal & got this error
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

/app/bin/primehack-wrapper: line 5:    13 Aborted                 (core dumped) dolphin-emu "$@"
![Screenshot_20231104_160938](https://github.com/shiiion/dolphin/assets/65131530/f41b2319-fe4c-43b3-b489-261ebd139335)
 & as you can see xwayland is on
FYI it work in x11 but i don't wanna use that

**Comment by SuperSamus** [comment]
It's an upstream issue: https://bugs.dolphin-emu.org/issues/11807

**Comment by Perisys1312** [comment]
Your best effort here is to get the xwayland package and see if that works, however that is still X in a sense.

**Comment by B-Nerd** [comment]
Ignore everything i posted it was a setting in flatseal called fallback to x11 windowing system
