### ISSUE TITLE
I will actually pay someone to update the flatpak to 1.0.7

### ISSUE THREAD

**Issue by esanscoopsers** [shiiion/dolphin#151]
if i build from source it doesn't work with wayland. the flatpak version works with wayland for some reason. this is all i want for christmas

also the reason it needs to be updated is that mouse clicks dont actually register in the current flatpack version. they do register in 1.0.7

**Comment by SirMangler** [comment]
Flatpak has been updated to 1.0.7: https://github.com/flathub/io.github.shiiion.primehack/commit/aeda3fb3dc2a8c45d9b472e7c643a563293b9b57
