### ISSUE TITLE
When will you please add support for Japanese version?

### ISSUE THREAD

**Issue by natraps1986** [shiiion/dolphin#153]
The early NTSC-U version have a lot bugs, while the latter ones cut some emenies off, the japanese version is some kind more well produced, but Primehack always ignore the NTSC-J version support, if you already give that up or may add them in the future? Thanks!

**Comment by hikagura99** [comment]
did you try playing on the pal versions? they run perfectly and i know they are 1:1 with the japanese versions

**Comment by SirMangler** [comment]
We have no plans to add support to the Japanese versions at this time. Some work was done by another developer but to our knowledge it wasn't ever completed.

**Comment by natraps1986** [comment]
No I haven't, but according to internet information, there is a hunter metroid&nbsp; missing in some ice cave in pal and later usa versions, which is important, may refer to the hunter metroid ds in some log, so the only versions which have it are original usa version and jap version, sadly the original usa version has tons of bugs.



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 5, 2024 02:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shiiion/dolphin] When will you please add support for Japaneseversion? (Issue #153)




 
did you try playing on the pal versions? they run perfectly and i know they are 1:1 with the japanese versions

**Comment by natraps1986** [comment]
Ok, thanks, for ngc versions, according to internet information, there is a hunter metroid  missing in some ice cave in pal and later usa versions, which is important, may refer to the hunter metroid ds in some log, so the only versions which have it are original usa version and jap version, sadly the original usa version has tons of bugs.


To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [shiiion/dolphin] When will you please add support for Japaneseversion? (Issue #153)




 
We have no plans to add support to the Japanese versions at this time. Some work was done by another developer but to our knowledge it wasn't ever completed.
