### ISSUE TITLE
Add Gyro support

### ISSUE THREAD

**Issue by GrzegorzDyrda** [shiiion/dolphin#154]
Would be great to have twin stick + gyro controls, just like in Metroid Prime Remastered on Switch.

I'm using a Switch Pro Controller on PC, and I'm surprised that PrimeHack doesn't support gyro, even though vanila Dolphin does.

Or am I missing something?

I know I could play around with Steam Input... But I'm talking about native PrimeHack gyro support - without the need for any external tools.

**Comment by SirMangler** [comment]
> I'm surprised that PrimeHack doesn't support gyro, ***even though vanila Dolphin does.***

PrimeHack is vanilla dolphin + metroid prime mods + new ui. We didn't remove any features. This is a question of configuration, there's a lot of different approaches to doing this. 

The rawest way to do this from the top of my head is to add the gyro input directly to the camera input in the Advanced Input menu. You can also apply modifiers, ie something to the effect of `Stick Up + (Gyro Pitch+ * 0.20)` (not actual bind names).

**Comment by SirMangler** [comment]
We may add some premade gyro controller configs to the wiki if anyone is interested in making them, however as of right now having built in gyro configs isn't currently planned.
