### ISSUE TITLE
 Build Crashes on mac os

### ISSUE THREAD

**Issue by devinlittle** [shiiion/dolphin#155]
when building with the command `cmake ..` the build fails at the end for the reason below
![image](https://github.com/shiiion/dolphin/assets/65364480/b00b785c-cfff-4a41-b497-c5d79f13e47b)

**Comment by Retropex** [comment]
Did you find any workaround for this @pixthehe ?

**Comment by devinlittle** [comment]
sorry for being really late to this but no I haven't. I just used a different build that I got from a year ago.
