### ISSUE TITLE
Stereo 3D causes the viewmodel to be displaced

### ISSUE THREAD

**Issue by thatsprettygood** [shiiion/dolphin#156]
![sbs](https://github.com/shiiion/dolphin/assets/36249601/0bdc1985-ae37-4783-9e95-b98697ed68cd)
This problem does not occur with the latest build of dolphin as of writing.

**Comment by SirMangler** [comment]
The upstream fix should be in the latest version of PrimeHack. Feel free to reopen this issue if it is still a problem.
