### ISSUE TITLE
Prime Hack 1.0.7a (Stand-alone MP3 Crashes when starting a new or loading an existing save file. Even with a good rom dump)

### ISSUE THREAD

**Issue by WanderingSpider** [shiiion/dolphin#172]
So, I don't know how this happened but after something I did in an MP3 Rando, I am unable to just load a save or start a new game on MP3 regardless of if it's a Rando or not, I even redumped a new rom, that I verified was considered a good dump by the emulator, but it always crashes in the same places. When loading an existing save, it crashes on the text that shows the area name and when starting a new save it crashes here.
![Crash](https://github.com/user-attachments/assets/1e8a162e-d1b7-4a5b-b97b-30a5e3d2790c)

I've tried everything I could to troubleshoot it, nothing I'm hoping someone has some info that could help.

**Comment by SirMangler** [comment]
Often problems like this can be solved by deleting your `Cache` folder and the `ini` files in your `Config` folder. On PrimeHack on Windows, this will be under `Documents/Dolphin Emulator/`.

If you want to maintain your settings and cache for some reason, you can also try adding a `txt` file called `portable` next to the primehack EXE. You can copy your saves over by coping the Wii and GC folder from the `Documents/Dolphin Emulator` folder to the newly generated `User` folder next to the exe once you start PrimeHack. 

I recommend asking in our [discord support channel ](https://discord.gg/tchQne2)if you would like faster responses for questions like this.

**Comment by WanderingSpider** [comment]
Thanks, It's working now.
