### ISSUE TITLE
Include better on-screen button prompts by default

### ISSUE THREAD

**Issue by NintendoManiac64** [shiiion/dolphin#173]
This is basically a follow-up from issue #137 since it's become clear that a single set of button prompts wouldn't work.

**Comment by SirMangler** [comment]
Right now designing a new system for button prompts, designing new icons and generating images for multibind icons, and the various engine changes to load custom images wide enough for the icons isn't in scope for PrimeHack. The '[Universal Dynamic Input](https://github.com/Venomalia/UniversalDynamicInput/wiki/Installation)' is currently the best solution for this, which currently can do everything short of displaying multi-binds in the prompts. The developer of this may be a better person to ask for adding multibind support.
