### ISSUE TITLE
Visor Change shortcut no longer working

### ISSUE THREAD

**Issue by Xelo2000** [shiiion/dolphin#19]
The Visor change shortcut (ex: E+1 for Scan Visor) is no longer working on the latest release. I should note that it does show up on the PrimeHack tab on the controller configs and it would appear that it does work, but there's no change in-game. I've only tested this on Metroid Prime 2.

**Comment by SirMangler** [comment]
This is probably due to the Visor 1 bind breaking in the refactor. You can press the number and *then* E or remove the default Visor 1 bind. You'll need to bind it elsewhere as it's used for Combat Visor (default). I have only experienced this in Prime 3, but its possible Prime 2 has it as well.

**Comment by halek** [comment]
Works after i bound LEFT | E to '-' on general options

**Comment by SirMangler** [comment]
fixed in https://github.com/shiiion/dolphin/commit/82399d2f580c7dada7247ee0349b8deee13efed8 and will be in 1.0.2 soon
