### ISSUE TITLE
Controller option on Primehack 1.0.1 not working correctly

### ISSUE THREAD

**Issue by ggermain1** [shiiion/dolphin#22]
When using controller mode, the cursor keeps sliding diagonally down-right. Also, can you allow the always enabled "Always Hide Mouse Cursor" configuration to be disabled if using a controller?

**Comment by SirMangler** [comment]
You need to increase your deadzone slightly. While the dot is red, it means Dolphin is receiving input from your stick. Just keep increasing it until it goes grey (usually somewhere between 3% and 10%). 

You can also try the "Calibrate" button and defining your stick's size exactly. Note, if you mess up the calibration you can reset it by selecting `Reset` in the dropdown on the `Calibrate` button.

**Comment by SirMangler** [comment]
> can you allow the always enabled "Always Hide Mouse Cursor" configuration to be disabled if using a controller?

We will consider this. If you create a new issue dedicated to that (or any) suggestion we can keep you posted on our thoughts and if we implement it.
