### ISSUE TITLE
Disable "Always Hide Mouse Cursor"

### ISSUE THREAD

**Issue by ggermain1** [shiiion/dolphin#23]
Can you allow the always enabled "Always Hide Mouse Cursor" configuration to be disabled if using a controller?

**Comment by SirMangler** [comment]
Before controller support, `Always Hide Mouse Cursor` wasn't ever needed to be off, hence us forcing it. 

I see us having two options to do this:
a) Simply remove the override and allow you to set it as normal. This is would reintroduce a problem we had before, with users asking us about how to stop that from happening or assuming it was our fault. We can leave the default option to have it off, but anybody who has used Dolphin previously will have it on.

b) Unlock the option only if Controller Mode is enabled. This seems like the best of both worlds to me.

**Comment by ggermain1** [comment]
Yeah, option b sounds great!

**Comment by SirMangler** [comment]
Resolved in: https://github.com/shiiion/dolphin/commit/3a4a0580c67932224ce39826144c436c22fe5573
