### ISSUE TITLE
Metroid Prime not starting

### ISSUE THREAD

**Issue by elclid** [shiiion/dolphin#25]
Fresh install of Prime hack and Metroid Prime 1 just shows a black screen when opened. Other games open fine.

**Comment by SirMangler** [comment]
This is very likely to be a problem with your game dump itself. You can verify it in the game properties window, under the `Verify` tab. [We have a glitches guide too.](https://github.com/shiiion/dolphin/wiki/Glitches-and-Bugs)

[Please see our discord for further (and far more efficient) support](https://discord.gg/tchQne2), until then I shall close this.
