### ISSUE TITLE
Compile error on ArchLinux at InputConfig.cpp

### ISSUE THREAD

**Issue by Linskun** [shiiion/dolphin#36]
Compile stop with error :
`/usr/bin/ld: ../InputCommon/CMakeFiles/inputcommon.dir/InputConfig.cpp.o: in function `InputConfig::LoadConfig(bool)':
InputConfig.cpp:(.text+0x1ac5): undefined reference to `HotkeyManager::ResetStupid()'
collect2: error: ld returned 1 exit status
make[2]: *** [Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui.dir/build.make:221: Binaries/dolphin-emu-nogui] Error 1
make[1]: *** [CMakeFiles/Makefile2:1565: Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
[primehack_compile_error.txt](https://github.com/shiiion/dolphin/files/5742386/primehack_compile_error.txt)
`

**Software information**

OS: Arch Linux x86_64
Resolution: 1920x1080
Dm/Wm: GNOME
gcc (GCC) 10.2.0

**System information**

- Kernel:** Linux 5.9.14-zen1-1-zen
- CPU: AMD Ryzen 5 1600X (12) @ 3.600GHz
- Memory: 16GB
- GPU: NVIDIA GeForce GTX 1060 6GB
- Driver: nvidia 455.45.01

[primehack_compile_error.txt](https://github.com/shiiion/dolphin/files/5742387/primehack_compile_error.txt)

**Comment by SirMangler** [comment]
This was a quick patch to fix a problem in the upstream making our defaults broken. It's interesting this occurs on Arch but not Windows. This wouldn't be required if this was merged: https://github.com/dolphin-emu/dolphin/pull/9358

I pushed a temporary fix here: https://github.com/shiiion/dolphin/commit/977d17ea7a29c3f874ac27bf925ec233176d7f08

You will want to unbind the default Hotkeys for Freelook if they start with `@(SHIFT +`.
