### ISSUE TITLE
Metroid Prime Trilogy reticle always staying off center of the screen

### ISSUE THREAD

**Issue by ohMoka** [shiiion/dolphin#40]
I'm at wits end with this bug, everything else with PrimeHack is working well except the crosshair is off center. Samus will still shoot in the direction her arm is facing, but the lock on snaps to the off center crosshair as well. Not really playable in this state unfortunately :-( 
![primehack reticle off center](https://user-images.githubusercontent.com/18376289/105781966-60a9bf80-5f28-11eb-8a80-9bf40ed10cc1.PNG)

**Comment by SirMangler** [comment]
Have you tried defaulting your settings? This may be a result of IR Point in motion simulation or Motion Input if you're using a controller.

Are you using a mouse+keyboard or controller mode?

**Comment by ohMoka** [comment]
This happens in both mouse + keyboard and controller mode. Thank you for the quick reply by the way :-)

**Comment by windyvalleyzone** [comment]
this is also happening to me, hope it can be resolved soon

**Comment by ohMoka** [comment]
I wasn't able to figure out anything with this, and only got one reply lol. Good mod, but unfortunately unplayable for me.

**Comment by AnthonyRyuki** [comment]
Are you using the widescreen hack or the game's built-in widescreen mode? The widescreen hack might be causing it.

**Comment by SirMangler** [comment]
Can you please try this on the [latest version of PrimeHack](https://github.com/shiiion/dolphin/releases/tag/1.0.3) and see if it persists? 

Note we also have new UI
![image](https://user-images.githubusercontent.com/4237834/113448195-46420580-93f3-11eb-8078-54a8e601e646.png)

**Comment by ohMoka** [comment]
I was excited to try but the bug still persists, regardless of the widescreen hack being enabled or not :/

**Comment by shiiion** [comment]
We have asked before, in more general terms, but to be sure, can you put Primehack in portable mode, and test again.

**Comment by windyvalleyzone** [comment]
It might be a problem with Dolphin in general, because both of my other
Dolphin copies started doing the same thing

**Comment by shiiion** [comment]
> 
> 
> I was excited to try but the bug still persists, regardless of the widescreen hack being enabled or not :/

Bump on my earlier request, if you did not see it.

**Comment by ohMoka** [comment]
Yes, portable mode fixes it! Not sure why it's happening in other Dolphin copies but it fixes it here in PrimeHack. Thanks for your help!
