### ISSUE TITLE
Prime 3 Control Reticle When Locked-On option not working

### ISSUE THREAD

**Issue by brawler14801** [shiiion/dolphin#43]
When playing the **standalone** version of prime 3 the control reticle when Locked-On option doesn't seem to do anything. Weirdly enough, I only have this problem on the NTSC-U version of the game. On the PAL version, it works perfectly.

**Comment by UltiNaruto** [comment]
Fixed in #45

**Comment by shiiion** [comment]
Confirmed fixed, closed.
