### ISSUE TITLE
MP1 GCN Beam effects Gecko codes?

### ISSUE THREAD

**Issue by AnthonyRyuki** [shiiion/dolphin#46]
Hi there! I'm a huge fan of the Metroid Prime series and I love this project.
One of my favourite features of it is the ability to re-enable MP1 Beam effects in the Trilogy version.
Is it possible to create Gecko codes that also make it possible to do on real hardware or on the main branch of Dolphin?
Thanks and keep up the great work.

**Comment by SirMangler** [comment]
Have you considered using our `Disable PrimeHack Controls` option? This allows you to use PrimeHack Graphics settings but keep the native controls.

It is possible to convert it into a very long Gecko code, but you need to convert 51 writes to gecko writes it by hand. Here is the file:
https://github.com/shiiion/dolphin/blob/master/Source/Core/Core/PrimeHack/Mods/CutBeamFxMP1.cpp

**Comment by AnthonyRyuki** [comment]
Thanks for the reply. I might try the option you suggested, but I was very interested in checking the effect out on real hardware.

So to convert it into a Gecko code, the first line of each column should be the address (that is, the first input value for the add_code_change method) and the second line should be the second input value for that method, right?

**Comment by AnthonyRyuki** [comment]
OK, so I've just tried that, and it does in fact work. However, the first two digits of the address columns, which are always "80" in that file, should be replaced with "04", because it tells that a 32-bit value should be written. I've attached a GCT file for the PAL version.
[R3MP01.zip](https://github.com/shiiion/dolphin/files/6221997/R3MP01.zip)

**Comment by SirMangler** [comment]
Issue has been resolved and solution was posted.
