### ISSUE TITLE
Image "Metroid Prime Loading..." flickers constantly, after some cutscenes.

### ISSUE THREAD

**Issue by maliquem** [shiiion/dolphin#48]
Wont go away after appears 

![image](https://user-images.githubusercontent.com/47405323/113584731-9db5c080-9601-11eb-8efc-d05b01689bbc.png)

**Comment by SirMangler** [comment]
https://github.com/shiiion/dolphin/wiki/Glitches-and-Bugs#visual-glitches

Please see the wiki page written for this error (and ones alike it). If you need more support, [please join our discord](https://discord.gg/tchQne2).

**Comment by Zopolis4** [comment]
Had same issue, and solved it via enabling Immediately Present XFB. Thought I would post this here, as the wiki page dosent show how to solve it.

**Comment by SirMangler** [comment]
> 
> 
> Had same issue, and solved it via enabling Immediately Present XFB. Thought I would post this here, as the wiki page dosent show how to solve it.

`Immediately Present XFB` is mentioned in the wiki as a potential solution *twice* on the visual glitches page but also isn't recommended for reasons such as introducing different visual glitches and not actually permanently solving it, as explained on that page. The guide was actually written specifically to solve the logo error specifically, among others like the flickering black bar error that `Immediately Present XFB` can cause. [The wiki page explains how to permanently solve the errors at the cost of performance](https://github.com/shiiion/dolphin/wiki/Glitches-and-Bugs#complete-stability-setup), [as well as alternate solutions that are more performance friendly. ](https://github.com/shiiion/dolphin/wiki/Glitches-and-Bugs#most-optimal-setup)

I mean no offence by this, but the only way somebody would still have visual glitches after following this guide is if they have made a user error, such as using savestates which already contain desyncs (which is explained at the top of the page), or they have not enabled the settings correctly, [such as selecting the wrong option type in the properties window](https://github.com/shiiion/dolphin/wiki/Glitches-and-Bugs#game-properties) or accidentally miss-configuring / missing parts of the guide. In which case, as mentioned the last part of the wiki, they can reset their settings and start again.
