### ISSUE TITLE
Primehack freezing when scanning on talon IV

### ISSUE THREAD

**Issue by jw6642** [shiiion/dolphin#5]
After landing on Talon IV the game completely freezes when scanning in the first room with the beetles.  Please advise how to fix.  I used the guide to setup everything and the space station fan flawlessly.

**Comment by SirMangler** [comment]
I cannot reproduce this. Please verify your dump by going to the game properties, `Verify` tab, and hitting `Verify Integrity`. If you're savestating, fully restart the game and do not use them while trying to resolve these problems. I also recommend trying another video backend.

For further support, please see our discord server:
https://discord.gg/tchQne2

**Comment by jw6642** [comment]
I changed my video back end from Direct X 12 to Vulcan and it appears to have fixed.  Also is there an issue with the discord @SirMangler ?  I joined but it never loads any channels?
