### ISSUE TITLE
Brief window to nothing

### ISSUE THREAD

**Issue by Emberson9000** [shiiion/dolphin#52]
Hi. I recently decided to download Primehack because I wasn't satisfied with the Metroid Prime Trilogy's current motion controls. Every time I go to click on the game now, it brings up a little window, and then closes it without opening Metroid Prime Trilogy. I am not able to find any online forums addressing this issue if they exist, despite searching with multiple ways of phrashing the question. I then installed another Primehack Launcher, and it did the same thing. I also tried vanilla Dolphin, which ran the game, but not with the control that Primehack supposedly offers. I'm led to believe that this is some sort of bug, and I would really appreciate if this were somehow fixed.

**Comment by SirMangler** [comment]
There's a few bugs that cause this in Dolphin, sometimes changing from OpenGL in Graphics will solve this. I suggest you try `D3D11`.

If this doesn't solve it, I recommend you clear your settings, this can be done easily by enabling `portable mode`, either in the updater or by creating an empty text file named `portable` next to `Dolphin.exe`. 

This isn't really related to PrimeHack itself, but if you would like more support on fixing it, [join our discord.](https://discord.gg/tchQne2)

**Comment by Emberson9000** [comment]
Thank you. I probably should've turned off Vulcan first. It runs now, and I'm sure any other issues are better documented should I have to troubleshoot.
