### ISSUE TITLE
Inputs not working when interacting with switches. 

### ISSUE THREAD

**Issue by MPrun** [shiiion/dolphin#54]
While playing MP3 Corruption the motion controls were bound to Shift and worked fine when interacting with the push, pull, rotate controls. But for some reason it's not working with the pump-system on one of the levels early in the game. While interacting with the pump, the configure window for the controller isn't showing any inputs are being received from the mouse and keyboard however I am still able to press the exit (space) button. Also the camera is able to be moved while interacting with the pump.
![image](https://user-images.githubusercontent.com/83432238/116626277-f2a2d900-a918-11eb-866c-34b05a211a30.png)

**Comment by SirMangler** [comment]
Please update to the latest version.

https://github.com/shiiion/dolphin/releases/tag/1.0.4

**Comment by MPrun** [comment]
Thanks, didn't know I was using an older version.
