### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by mac-a-r0ni** [shiiion/dolphin#58]
It is my understanding that dolphin now supports M1 machines. I'm not really familiar with PrimeHack enough to update the included dolphin myself, as I'm unaware of the changes made. But if the project were updated to include the newer dolphin, I'd love to try and put together a Mac build of PrimeHack for you.

I didn't see another way of contacting, so my apologies for creating an issue report.

**Comment by SirMangler** [comment]
PrimeHack physically does not fully support Mac even if you compiled it. Neither me or shio have a Mac to implement the support or to test it. All that's needed is someone to create a mouse input class for Mac's input API and to hook it up.

https://github.com/shiiion/dolphin/wiki/Frequently-Asked-Questions#what-platforms-is-primehack-on
