### ISSUE TITLE
Suggestion: allow BOTH mouse and controller

### ISSUE THREAD

**Issue by daninthemix** [shiiion/dolphin#6]
It's great to have the controller option, but some parts of Prime 3 are literally unplayable with a controller - notably when welding some circuit boards, and also trying to shoot the zipline enemies before they knock you off.

There, could controller plus mouse be an option?

**Comment by SirMangler** [comment]
The described problems have been resolved in later updates. This is a hack solution with little applicability outside what was fixed.

**Comment by dbenoy** [comment]
Believe it or not some people use both at once. Here's a picture of my left hand while I'm playing. The elastics keep the controller from sliding around:
![1024-1365](https://user-images.githubusercontent.com/2285331/113492073-50bbd800-94a3-11eb-8e6c-70d1c83282b6.jpg)
I get access to analog control, where I can get a full 360 degree movement direction and the ability to move slowly, AND the precision of a mouse. It's quite nice. It's how I play all shooters.

To play PrimeHack (and lots of other games that don't support both at once) I just use a program to convert my joystick to the 8-direction keyboard inputs. It doesn't feel very good, especially when I'm doing some morph ball precision movement or something, but it's fine. Very noticeable but not going to ruin the experience. It's kinda like being limited to stereo sound when you have surround speakers. It's not the biggest deal in the world, but you can definitely notice the difference.

Honestly though I'm delighted enough that I can play with my mouse at all, so I'm quite grateful for what I got! But there actually are uses for this outside of fixing those problems @daninthemix mentioned.

**Comment by dbenoy** [comment]
For anyone looking for how to do this in the later updates, right click on the up/down/left/right inputs, and then you can use the drop-down at the top to override and specify another device. Pick your controller, and find the axis you want in the list and click 'select'.
