### ISSUE TITLE
Changing beams crashes the game (GameCube randomised version)

### ISSUE THREAD

**Issue by ShawnSigma** [shiiion/dolphin#62]
Today a dev helped me get Metroid Prime 2 Randomizer to work with PrimeHack... at first.
The game starts and runs fine, the mouse controls are great and I didn't see any visual bugs. The only problem is that the game will crash whenever I try changing beams, showing this screen and freezing:

![Exception 3](https://user-images.githubusercontent.com/54847049/123563184-2a0ff380-d7ab-11eb-857c-9f328125540f.png)

I tried messing around with some graphical and memory settings but the only different result I got was when I tried using the memory override feature: instead of showing the red exception screen and freezing, the game just froze in the middle of the animation without showing any screen and while making a _lovely_ noise I'm sure you know very well.

This does not happen in the regular version of Prime 2 so it must have something to do with the randomised ROM. Any ideas?

**Comment by ShawnSigma** [comment]
### Update: 
I was able to solve this problem by switching from Direct3D11 to OpenGL as my backend (_I've also tried every other setting, OpenGL was the only one that worked_)
Luckily the emulator crashed when trying to stop the emulation, showing that the problem had something to do with the backend, so I knew I'd have to focus on that. I'm still not sure about the specific cause of the problem, so that might still be worth looking into.

Here's a screenshot I was able to take before the emulator crashed (the text I censored is just the path to the emulator):
![MS Visual C++ Runtime Library - Assertion failed](https://user-images.githubusercontent.com/54847049/123629251-fadd9e80-d80b-11eb-8dc9-0101f3767f8d.png)

**Comment by ShawnSigma** [comment]
###Update 2:
Defeating the first Dark Samus also crashes the game, it happens right after the cutscene

![Exception 2](https://user-images.githubusercontent.com/54847049/123633753-83ab0900-d811-11eb-9c19-777b3212bee4.png)
![MS Visual C++ Runtime Library - Assertion failed again](https://user-images.githubusercontent.com/54847049/123633758-8574cc80-d811-11eb-9fc8-c58f2b749ade.png)

**Comment by shiiion** [comment]
Rando and Primehack are known to conflict, not sure what though. I can look into this, but I need to generate a randomizer iso and try to get crashing to occur. It could be any number of things we do to the game with the expectation that certain addresses are what they should be, and certain behaviors are consistent (which likely get changed by randovania).

**Comment by ShawnSigma** [comment]
### Update 3

I was able to kind of solve this problem by disabling PrimeHack controls, starting the game, creating a savestate once I gain control of Samus, quitting, enabling PrimeHack controls again, starting the game and loading the savestate. I've since completed several different seeds and it all works perfectly, so the problem seems to come from the moment you start gameplay for some reason.
This seems to be a combined issue of both PrimeHack and Randovania, the randomiser I used

**Comment by SirMangler** [comment]
A bunch of fixes for randomiser were added: https://github.com/shiiion/dolphin/commit/923f5e2f68049463de69007734ec8c27ecb246ba

Does this resolve the problem?

**Comment by ShawnSigma** [comment]
> A bunch of fixes for randomiser were added: [923f5e2](https://github.com/shiiion/dolphin/commit/923f5e2f68049463de69007734ec8c27ecb246ba)
> 
> Does this resolve the problem?

I haven't tried Prime 1 Rando yet but Echoes no longer crashes when starting or in-game, so it looks like it might be fixed

**Comment by ShawnSigma** [comment]
Another problem I hadn't mentioned was that closing the game also caused the entire emulator to crash, something that hasn't happened once with version 1.0.5 so far, so things are looking good

**Comment by vyuuui** [comment]
Cleaning up issues, I'll tentatively close this.
