### ISSUE TITLE
"Wii remote Disconnected by Emulated Software"

### ISSUE THREAD

**Issue by YellowInkling** [shiiion/dolphin#63]
Everytime I try to play this error message keeps showing up and it won't let me play. How do i fix this?
![image](https://user-images.githubusercontent.com/74347915/124443776-129bc080-ddd2-11eb-9414-9f6252c3089c.png)

**Comment by SirMangler** [comment]
This should be resolved in the next version. You should try clearing your settings if not, this can be effectively done by adding a `portable.txt` file to your dolphin.exe folder. If this does not resolve the problem, please continue this on our [Discord](https://discord.gg/tchQne2).
