### ISSUE TITLE
Trilogy Echoes: Strange Spider-Ball Physics

### ISSUE THREAD

**Issue by zachHixson** [shiiion/dolphin#64]
I've been having a really strange issue playing Echoes where, when stuck to a spiderball track, I'm being repelled from the track in different directions.

I played through Echoes about a year ago and don't remember this being a problem so I'm not sure what changed.

Here's a video of the issue: [https://youtu.be/pfKzU349Zm8](https://youtu.be/pfKzU349Zm8)

In the video it's first visible when I'm upside down and release the stick, it pushes me backwards along the track. I then try to drop down to the bottom of the C shaped track, and it pushes me back to the top one. Finally I try to cross the gap only for the spider ball to start launching me off the track vertically.

**Comment by zachHixson** [comment]
Never mind, this was due to an issue where I accidentally enabled a moonjump Gecko code for Prime 3, which for some reason didn't affect Prime 1, but affected Prime 2.

**Comment by SirMangler** [comment]
> 
> 
> Never mind, this was due to an issue where I accidentally enabled a moonjump Gecko code for Prime 3, which for some reason didn't affect Prime 1, but affected Prime 2.

The gecko codes are unofficial, they're downloaded from an external website and yeah, most of them don't actually check what game you're running, so many bugs can be caused by them including totally crashing the Trilogy menu.
