### ISSUE TITLE
Issue with compiling on arch linux.

### ISSUE THREAD

**Issue by qweri0p** [shiiion/dolphin#65]
When attempting to compile primehack I got this error. This error occured both on my pc and my laptop. This error is exclusive to primehack as I did not have this issue when compiling regular dolphin.

This error occured while running "make" in the build directory. 

`
[100%] Linking CXX executable ../../../Binaries/dolphin-emu`
`/usr/bin/ld: ../InputCommon/CMakeFiles/inputcommon.dir/XInput2Mouse.cpp.o:(.bss+0x0): multiple definition of 'win_hdl'; CMakeFiles/dolphin-emu.dir/RenderWidget.cpp.o:(.bss+0x0): first defined here`
`/usr/bin/ld: ../InputCommon/CMakeFiles/inputcommon.dir/XInput2Mouse.cpp.o:(.bss+0x8): multiple definition of 'win_h'; CMakeFiles/dolphin-emu.dir/RenderWidget.cpp.o:(.bss+0x8): first defined here`
`/usr/bin/ld: ../InputCommon/CMakeFiles/inputcommon.dir/XInput2Mouse.cpp.o:(.bss+0xc): multiple definition of 'win_w'; CMakeFiles/dolphin-emu.dir/RenderWidget.cpp.o:(.bss+0xc): first defined here`
`/usr/bin/ld: ../InputCommon/CMakeFiles/inputcommon.dir/XInput2Mouse.cpp.o:(.bss+0x10): multiple definition of 'win_y'; CMakeFiles/dolphin-emu.dir/RenderWidget.cpp.o:(.bss+0x10): first defined here`
`/usr/bin/ld: ../InputCommon/CMakeFiles/inputcommon.dir/XInput2Mouse.cpp.o:(.bss+0x14): multiple definition of 'win_x'; CMakeFiles/dolphin-emu.dir/RenderWidget.cpp.o:(.bss+0x14): first defined here`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [Source/Core/DolphinQt/CMakeFiles/dolphin-emu.dir/build.make:2888: Binaries/dolphin-emu] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:1721: Source/Core/DolphinQt/CMakeFiles/dolphin-emu.dir/all] Error 2`
`make: *** [Makefile:156: all] Error 2
`

I have also attempted to install the [AUR](https://aur.archlinux.org/packages/dolphin-emu-primehack-git/) package but that also gave me the same error.

**Comment by SirMangler** [comment]
Please attempt to recompile now. It should be resolved.

**Comment by qweri0p** [comment]
Its fixed now. Thx.
