### ISSUE TITLE
3-pixel visual artifact at center screen during cutscenes

### ISSUE THREAD

**Issue by JPLeBreton** [shiiion/dolphin#66]
See this shot:
![mp2_glitch](https://user-images.githubusercontent.com/263303/132504893-81e9d2e7-a8c6-400f-b3af-a230b019f84c.jpg)

And a closeup:
![mp2_glitch_closeup](https://user-images.githubusercontent.com/263303/132504918-9c7bdfa2-c934-432d-bbca-642ff01c3245.png)

Could be crosshair-related, as I don't see it during normal gameplay.

**Comment by SirMangler** [comment]
This is a bug in Dolphin with increasing the internal resolution of the game. We resolved it for gameplay by fixing textures that some members of the prime modding community found to be the cause. But this only applies for gameplay, and not cutscenes or menus. Until the remaining problem textures are found, we can't solve this problem aside from telling you to lower your internal resolution.
