### ISSUE TITLE
[QUESTION/SUGGESTION/REQUEST] GameCube view bobbing

### ISSUE THREAD

**Issue by ShawnSigma** [shiiion/dolphin#69]
I don't suppose it would be possible to have the view and arm cannon bob while moving in the GameCube versions of Prime 1 and 2 like they normally do?

I'm sure it was hard enough to get full mouselook movement to work in the first place, but I wish it didn't sacrifice the bobbing. I doubt it's possible but what do I know

I'm sorry if this is too unreasonable a thing to ask

**Comment by vyuuui** [comment]
This should be addressed with the latest commit, sorry for delay in implementation.
