### ISSUE TITLE
Stuck in home menu

### ISSUE THREAD

**Issue by nyanpasu64** [shiiion/dolphin#7]
When pressing alt+enter to enter/exit full screen, I accidentally opened the home menu. When I alt+tabbed to another window and started clicking around, I accidentally pressed the reset key. And now I cannot move my mouse in a way to exit the reset menu.

Video at https://youtu.be/Gpsr47zlRp0 . Note that my ffmpeg concatenation didn't quite work right.

**Comment by nyanpasu64** [comment]
Hmm, the home menu is unbound if you create a fresh Dolphin profile for PrimeHack (by creating `portable.txt` next to Dolphin.exe). But it's not unbound for existing Dolphin profiles because #8.

**Comment by SirMangler** [comment]
Answered in:
https://github.com/shiiion/dolphin/issues/8#issuecomment-640029014
