### ISSUE TITLE
Metroid Prime Trilogy won't open in PrimeHack but will open in other Dolphin builds

### ISSUE THREAD

**Issue by SupahDrivah1234** [shiiion/dolphin#70]
My MPT iso is able to open and load just fine in other Dolphin builds except PrimeHack, where clicking it open will reveal a very small black window that's open for half a second before disappearing, and nothing else happens.

**Comment by Shunfer** [comment]
I can't even find or know what this Portable mode is to try this fix?

**Comment by Shunfer** [comment]
Nevermind i found it and yeah it did not fix the issue only difference is that the black screen just flashes on the screen instead getting stuck for awhile. Please anyone find a fix or at least a reason why this is occuring?

**Comment by shiiion** [comment]
Check if you are running an antivirus, if so disable it. It’s known to cause this exact issue.

**Comment by Shunfer** [comment]
Yay! Thank you that seemed to be the fix, Such asimple step and i didn't think of it. :D
