### ISSUE TITLE
Hang when quitting to main menu

### ISSUE THREAD

**Issue by treacherousfiend** [shiiion/dolphin#72]
When going into the menu and quitting to return to the Prime Trilogy main menu, the emulator plays a loud sound (which I believe is the GC/Wii crashing noise?) before going to a black screen and hanging.
Attempting to stop emulation while in this state also fails, requiring the user to force stop.

I've only tested MP1, but its possible that it happens on the other games as well.
This doesn't happen on the current dev build of Dolphin, it only happens on Primehack.

**Comment by SirMangler** [comment]
If this is still a problem in the latest version (1.0.7), please reopen this issue.
