### ISSUE TITLE
Control/Hotkeys collision on Tab

### ISSUE THREAD

**Issue by Formedras** [shiiion/dolphin#76]
The key used by PrimeHack for "Map" is also the default key used by Dolphin for "Disable Emulation Speed Limit" (I will refer to this as "speedup"). This results in opening the map also doubling as speedup (on sufficiently-powerful computers).

**Suggested course of action**: Change the default key for speedup to something innocuous that neither PrimeHack nor Dolphin mainline uses. My personal choice was End.

**Comment by SirMangler** [comment]
Resolved: https://github.com/shiiion/dolphin/commit/8a8f2f057d1128f5f2be321b92b0316c4dd8d76b
