### ISSUE TITLE
Have a button for "Shaking Wiimote"

### ISSUE THREAD

**Issue by Miepee** [shiiion/dolphin#79]
In MP3C, there are certain moments where the game expects you to shake the wiimote. This is for example when Gandrayda jumps at you, or the Metroid Hatcher catches you. Currently, the only workaround for this is "don't get hit by the attacks".

**Comment by SirMangler** [comment]
For this we would like to implement a "proper" control for this, since wiimote shake can be visually janky. You can add those shake controls in yourself in the Emulated Wii Remote tab, but naturally this is just a work around.

**Comment by SirMangler** [comment]
We now have native controls for all motion segments. You can jump to shake off Gandrayda.
