### ISSUE TITLE
[Feature Request] Use Dynamic Input Texture Packs for button prompts

### ISSUE THREAD

**Issue by Miepee** [shiiion/dolphin#80]
Not sure at all how viable this is, but it would be nice if PrimeHack would replace the button prompts the prime games uses with ones from the current control device.

**Comment by Formedras** [comment]
I would assume this would be outside the current scope of PrimeHack. (It also doesn't help that Prime 1 and 2 have different controls for visors and beams between GameCube and Wii. This complicates things a bit.)
That said, there is already a pack for this as part of the [Metroid Prime Trilogy HD Interface texture pack](https://forums.dolphin-emu.org/Thread-metroid-prime-trilogy-hd-interface-textures-v-1-7-may-01-2021). It is limited by the fact that said pack requires a specific (non-default) control scheme.

But for anyone looking to do this a bit better, I'd recommend also looking at both [Resource Packs](https://github.com/dolphin-emu/dolphin/blob/master/docs/ResourcePacks.md) and [Dynamic Input Textures](https://github.com/dolphin-emu/dolphin/blob/master/docs/DynamicInputTextures.md).

**Comment by SirMangler** [comment]
Seeing as a pack already exists for this, and no further activity has been made in this issue, I am going to close this. If somebody would like to suggest an enhancement to the existing system that PrimeHack could provide, then please open a new issue. At this point, we have no intention of designing our own icons and input pack.
