### ISSUE TITLE
Removed feature (bug?)

### ISSUE THREAD

**Issue by antichamber** [shiiion/dolphin#83]
In version 1.0.4, pressing the map key (in my case, TAB) would increase emulation speed to the maximum it could handle. I'm not sure why, but this does not happen in 1.0.5 . I'm not sure if this is an unintended behavior, but It greatly improved the experience for me by reducing the length of annoying cutscenes (an example being the elevator and save stations in MP1). Was this a feature? How can I make it work again in 1.0.5?

**Comment by SirMangler** [comment]
This is just a hotkey to unlock the speed limit. The option it changes is in `Config`, called `Speed Limit`. The hotkey was unbound because it conflicts with the Map key. You can easily bind it to anything you want in the top bar: `Options > Hotkeys`.
