### ISSUE TITLE
Unable to use Shift as lock on...

### ISSUE THREAD

**Issue by TheOldKingCole** [shiiion/dolphin#84]
Pressing shift leaves me unable to also use W and thus move forward while locked on.

**Comment by TheOldKingCole** [comment]
Oh also I noticed that you can now use the gamecube versions, do those have free look?

**Comment by SirMangler** [comment]
I'll quote from our Discord's pins. 
![image](https://user-images.githubusercontent.com/4237834/147741375-59f9c1ce-c96c-420f-bdaa-7829264c732a.png)

This was a mistake we inherited from mainline Dolphin. You should unbind the hotkeys in the `Game Boy Advance` tab.

> Oh also I noticed that you can now use the gamecube versions, do those have free look?

We have supported GameCube for a year and a half now, and they have all the main features that Trilogy/Wii does, this includes the mouse and dual-stick aiming. 

If you mean `Free Look` as in the Dolphin setting to move the camera artificially, this works for all prime games as far as I'm aware, but we didn't make that..
