### ISSUE TITLE
[Question/Suggestion/Off-topic..] Primehack DS?

### ISSUE THREAD

**Issue by Koppajin** [shiiion/dolphin#85]
Since I don't know of any other way to contact the devs of this I'd like to ask: are there any forks out there of DeSmuME or MelonDS that give Prime Hunters this treatment? Has any dev here thought about it?

**Comment by SirMangler** [comment]
It's certainly possible, I don't personally know of any forks that do this though. The main hurdle is finding someone dedicated enough to the game to reverse engineer the camera code, so like primehack you could write a mod into the emulator that takes the mouse input and writes it to the camera values each frame. 

If hunters already has an established modding/reversing community, part of this work may already be done. If you can find a community like that, I would ask there, they could always use PrimeHack as a reference.

**Comment by Koppajin** [comment]
@Arisotura
