### ISSUE TITLE
Request: Support vr

### ISSUE THREAD

**Issue by jvook** [shiiion/dolphin#88]
Metroid prime trilogy would work really well in virtual reality

**Comment by ProfessionalismIsMyMiddleName** [comment]
It's already more or less possible apparently, there are some modified versions of dolphin that can work in VR. Without all the primehack enhancements of course.

With that said, from what I heard it doesn't work as well as you would think, out of the box at least. The main issue is that your gun arm is not a real 3d object in game, samus has no full character model in first person. That makes the gun arm appear glued to your eyes in VR, which is very jarring.

With that said, I fully support this feature, I think it COULD work really well, with probably a huge amount of work spent fixing those issues.

**Comment by SirMangler** [comment]
This would be very cool but is out of scope for PrimeHack. It would be better to push for this in upstream Dolphin, then ask us to make mods specifically for Metroid Prime using that feature.
