### ISSUE TITLE
Unable to move or resize window in window mode

### ISSUE THREAD

**Issue by robross0606** [shiiion/dolphin#95]
When running in windowed mode, it seems to be impossible to either resize or drag the window because PrimeHack immediately grabs the cursor and then actively shoves the whole thing to the bottom right side of the screen.  When resizing, this immediately makes the window tiny and it cannot be made large again.  When trying to drag the window, this equally shoves the entire window off screen to the bottom right of the display.  Is there any way to "unlock" the grabbed mouse cursor in PrimeHack so you can do things with the window and then re-lock it to the controls?  This reminds me very much of how VMWare has special keyboard commands to lock/unlock the cursor between the host and guest if you want.  Otherwise, you're left with PrimeHack battling Windows for cursor control.

**Comment by shiiion** [comment]
Is this happening with the "render to main window" setting, or is it happening without it?

**Comment by robross0606** [comment]
Without it. I have not tried with render to main window enabled yet.

**Comment by SirMangler** [comment]
Are you on Windows or Linux? Currently on Windows, we use Dolphin's built in mouse locking solution. On Linux, we move the cursor to the centre of the window each frame, which could cause this problem.

**Comment by robross0606** [comment]
Windows 10

**Comment by SirMangler** [comment]
We will need to confirm if this problem is caused by us or **upstream**. If it's an [upstream ](https://github.com/dolphin-emu/dolphin) bug, then while we may be able to resolve it, this is an issue inherent to Dolphin itself and not an issue caused by us.

**Comment by robross0606** [comment]
Okay, lemme know if I can provide more details or info.

**Comment by SirMangler** [comment]
Please reopen this issue if it is still an issue in the latest version (1.0.7).
